language: python

python:
  - "3.6"

install:
  - pip install codecov coverage
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -s test -p 'test_*.py'

after_success:
- codecov
